### ISSUE TITLE
Info : 'onTreeEvent' event requirements 

### ISSUE THREAD

**Issue by asithw** [nextjs-boilerplate/react-tree-renderer#3]
This is great tree-renderer package. I am finding way to get level of a node in tree view .
is there any configuration for onTreeEvent event ?  it doesn't fire for my data.

`<TreeRenderer Template={DefaultTemplate} data={root} onUpdateData={onUpdateData} onTreeEvent={onTreeEvent} />`

**Comment by postor** [comment]
@asithw Added event example, trigger event in template https://github.com/postor/react-tree-renderer/blob/e2af6d5ab1c5a4c49438610c0a91023fd458de6d/examples/basic/pages/event.js#L22 and you get callback in onTreeEvent on Renderer https://github.com/postor/react-tree-renderer/blob/e2af6d5ab1c5a4c49438610c0a91023fd458de6d/examples/basic/pages/event.js#L97 
it shall log something like this, path is undefined if it's top level
```
{"eventData":{"data":"example"},"eventType":"closeAll","path":"children.0.children.1.children.0"}
```

Of course there is an easier way if you just need level of the node, just a preprocess, to assign each data a level
```
{
        title: 'root',
        children: [...]
}
```
to 
```
{
        title: 'root',
        level: 0,
        children: [...]
}
```
